### PR TITLE
Support multiple types in array

### PR DESCRIPTION
**Pull request by AlexBroadbent**
A generic `List` of a base class can explicitly specify valid
implementation classes used at runtime through the
`@JsonSchemaArrayItems` annotation.

The `JsonSchemaArrayItems` accepts a value of Classes that can be
allowed within the List.

An example implementation has been added through the unit test for the
model class `PolymorphicArrayWithSubtypes`, where a base class
`ABaseType` has three implementation classes `FooType`, `BarType`, and
`EggType`. The variable in the class `List<ABaseType> fooOrBarList` has
been annotated with
`@JsonSchemaArrayItems({FooType.class, BarType.class})` to signify
that when serializing into a JSON-Schema that only `FooType` and
`BarType` classes should be allowed and therefore validation should fail
if an `EggType` object is used.

[mbknor/mbknor-jackson-jsonSchema#82]

### CODE REVIEW

**Comment by mbknor** [comment]
Thanks for the PR. I'm looking into it --- and the ticket.

**Comment by AlexBroadbent** [comment]
As a caveat, the above code change is not a complete solution to my problem - but a use case in and of itself. This allows for only a given set of implementation classes to be used within a polymorphic deserialization - but it is not explicit to using the classes defined in the `JsonSchemaArrayItems`. 

For example: in the above review, the situation given is a list of `ABaseType` objects, where there are `FooType`, `BarType`, and `EggType` implementations. Specifying the annotation `@JsonSchemaArrayItems({FooType.class, BarType.class})` allows any combination of `FooType` and `BarType` objects in the given list such that:

Operand 1 | Operand 2 | Valid
---|---|---
FooType | BarType | &check;
FooType | FooType | &check;
BarType | BarType | &check;
EggType | BarType | &cross;

Where my original aim is to limit the list to exactly the given types in order, such that:

Operand 1 | Operand 2 | Valid
---|---|---
FooType | BarType | &check;
FooType | FooType | &cross;
BarType | BarType | &cross;
EggType | BarType | &cross;


In the output JSON schema, the `items` of the list still uses `oneOf` to allow any combination of the allowed objects. I am looking at taking this out and instead using just an array of the `ref$` objects to the permitted polymorphic classes.

**Comment by AlexBroadbent** [comment]
Last commit was just a clean up to the first commit.

Upon writing the changes to try and cover what I outlined in the last comment - I realised two things:

1. Specifying exactly only those classes is possible, through changing `MyJsonFormatVisitorWrapper.node` to be a JSON object or an array (as the `items`needs to be an array of `ref$` objects) instead of using a `oneOf` object.

1. The order of "items" in the JSON schema is defined by the ordering in the `JsonSubTypes` annotation list on the base class. 


The latter point really stopped me, as I was hoping that the `@JsonSchemaArrayItems` annotation would also handle the ordering. My usage is having the list of base classes in multiple places but with different permitted implementation classes, that also have a predefined order.

I found a workaround for the issue, where I can control the ordering - but it violates the entire visitor pattern used within the serializer - as it just pushes in all of the items when in `expectObjectFormat` if there are some `arrayItems` to push in.

**Comment by AlexBroadbent** [comment]
Added support for specifying base classes in the `@JsonSchemaArrayFilter` annotation, where all implementation classes will be written into the JSON schema.

**Comment by mbknor** [comment]
Hi,

I'm having some trouble understand which problem you
are trying to solve in this PR.

To investigate, I "disabled" your changes in **JsonSchemaGenerator** by NOT calling
your function **extractArrayItemTypes()**.

Then I ran your tests, to figure out what they where trying to assert.

Here are some comments - on each test:

**test("Multiple types within a polymorphic array")**

Here you have used Jackson-annotations to say that 
the class **ABaseType** can be of the following sub-types FooType, BarType and EggType.
Then you "override" that using your new custom annotation JsonSchemaArrayFilter to say
that you only want the schema to contain two of those types.

When I run this test with your modifications disabled,
the original **JsonSchemaGenerator**-implementation generates a jsonSchema correctly containing
these three types. Your test fails since you are asserting only two types.

If I just remove the Jackson JsonSubTypes-annotation for EggType, then your test succeeds.

To me your solution is to do just that.. What is the point of Telling jackons to be able to parse
three types, if you only want to of them?


**test("Inherited types within a polymorphic array")**

Here you have the class ABase2Type, which is jackson-annotated to have 4 sub-types.
You have also introduced the intermediat ASubType-type.
Again, I don't understand why you do not just use Jackson-annotations to annotate which types you would
Like to be able to parse..


I cannot continue with this PR before I understand what your are trying to do here..

**Comment by mbknor** [comment]
closing this one since I think it is a to special usecase

**Comment by Gigaclank** [comment]
I know this is an old MR. but i think this is a useful feature and would like to vote to reopen this and merge.

**Pull request closed without merging**
