### PR TITLE
Allow to inject custom schema key/value pairs

### PR DESCRIPTION
**Pull request by bbyk**
The schema spec is nuanced. Developers need to have a tool to a fine grain access over injecting schema attributes.

### CODE REVIEW

**Comment by mbknor** [comment]
Hi, and first of all: Thanks for your interest in this project.

What is the difference between these two annotations and the existing @JsonSchemaInject-annotation?

**Comment by bbyk** [comment]
I started my changes before `@JsonSchemInject` and the release them to you was delayed by an internal review :) The difference is stylistic only:

```
@JsonSchemaValues(stringValues = {
  @JsonSchemaStringValue(path = "items.pattern", value = "[a-z]+")),
  @JsonSchemaStringValue(path = "items.x-schema-form.type", value = "textarea"))
  @JsonSchemaIntValue(path =    "items.x-schema-form.length", value = 20))
})
public List<String> values;
```
vs
```
@JsonSchemaInject(json = "{\"items\": { \"pattern\": \"[a-z]+\", \"x-schema-form\": {\"type\": \"textarea\", \"length\": 20}}}")
public List<String> values;
```

**Comment by bbyk** [comment]
Maybe both approaches can be useful. `JsonSchemaInject` looks good in Scala with its multiline support. I don't know.

**Comment by mbknor** [comment]
I agree. We include both, but i think we should 'merge' them like this:

I think we only should have one 'main' inject-mechansim:
Add JsonSchemaStringValue and JsonSchemaIntValue as @JsonSchemaInjectString/@JsonSchemaInjectInt/ to @JsonSchemaInject.

Then, when processing @JsonSchemaInject, we first parse optionally json-property (default it to {}), then we add/inject all the maybe-existing @JsonSchemaInjectStringValue/@JsonSchemaInjectIntValue to that. 
Then we merge the final inject-data into the main schema.

We should also update the readme.

What do you think? Is this something you would be willing to do?

-Morten

**Comment by bbyk** [comment]
Sounds good.

> What do you think? Is this something you would be willing to do?

Sure. I am on it.

**Comment by mbknor** [comment]
:+1:

**Comment by bbyk** [comment]
Updated the code.

**Comment by mbknor** [comment]
thanks. looks good. The only think missing is a small update to README.md

**Comment by bbyk** [comment]
Good catch. Fixed.

**Comment by mbknor** [comment]
Thanks a lot!

**Comment by bbyk** [comment]
Thank you, Morten! When are you planning on making the next release?

**Comment by mbknor** [comment]
I'll try to so it tonight

**Comment by mbknor** [comment]
1.0.17 has just been released and will be available for download sooner than in search :)

**Comment by bbyk** [comment]
Thanks much!

**Pull request merged**
